services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - edge-network
    restart: unless-stopped

  receiver:
    image: haafizmh/edge-cicd-receiver:latest
    container_name: receiver
    depends_on:
      - mqtt-broker
    networks:
      - edge-network
    restart: unless-stopped

  gateway:
    image: haafizmh/edge-cicd-gateway:latest
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - receiver
    networks:
      - edge-network
    restart: unless-stopped

  web-server:
    build: ./web
    container_name: web-server
    ports:
      - "8000:8000"
    networks:
      - edge-network
    restart: unless-stopped

networks:
  edge-network:
    driver: bridge
