services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ../services/mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      edge-network:
        ipv4_address: ${MQTT_IP}
    restart: unless-stopped

  receiver:
    image: haafizmh/edge-cicd-receiver:latest
    container_name: receiver
    depends_on:
      - mqtt-broker
    networks:
      edge-network:
        ipv4_address: ${RECEIVER_IP}
    restart: unless-stopped

  gateway:
    image: haafizmh/edge-cicd-gateway:latest
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - receiver
    networks:
      edge-network:
        ipv4_address: ${GATEWAY_IP}
    restart: unless-stopped

networks:
  edge-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${EDGE_SUBNET}
